### ISSUE TITLE
Add coloring to items [Feature]

### ISSUE THREAD

**Issue by Danster2020** [Smalands-Nation/register-rs#11] opened 2022-09-01 11:24 UTC
Examples:

- Make all snacks one color and all ciders another.
- add icons to items

![image](https://user-images.githubusercontent.com/14301553/187902590-4b238aa4-a90f-41e1-a565-8da86cf95df8.png)

**Comment by Strosel** [comment] 2022-09-01 13:26
Duplicate of #9 
Closing

**Closed as completed by Strosel** 2022-09-01 13:26 UTC
